/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emlak_takip;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ubeyd
 */
public class musteriler extends javax.swing.JFrame {

    /**
     * Creates new form musteriler
     */
    VeriTabani vt = new VeriTabani();
     TabloBilgisi tb=new TabloBilgisi();
    public Giris parent;
    public musteriler() {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
        tb.MusteriTablosu(tb_musteriler);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_ad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_soyad = new javax.swing.JTextField();
        txt_tel = new javax.swing.JTextField();
        txt_mail = new javax.swing.JTextField();
        bt_ekle = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_musteriler = new javax.swing.JTable();
        bt_guncelle = new javax.swing.JButton();
        bt_sil = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMLAK TAKİP SİSTEMİ");

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("İsim*:");

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Soyad*:");

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefon*:");

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mail :");

        bt_ekle.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bt_ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emlak_takip/icons8-ok-50.png"))); // NOI18N
        bt_ekle.setText("Müşteri Ekle");
        bt_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ekleActionPerformed(evt);
            }
        });

        tb_musteriler.setBackground(java.awt.Color.lightGray);
        tb_musteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_musteriler);

        bt_guncelle.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bt_guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emlak_takip/icons8-edit-50.png"))); // NOI18N
        bt_guncelle.setText("Müşteri Düzenle");
        bt_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_guncelleActionPerformed(evt);
            }
        });

        bt_sil.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        bt_sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emlak_takip/icons8-trash-50.png"))); // NOI18N
        bt_sil.setText("Seçilen Müşteriyi Sil");
        bt_sil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_silMouseClicked(evt);
            }
        });
        bt_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_silActionPerformed(evt);
            }
        });

        label1.setBackground(java.awt.Color.darkGray);
        label1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("MÜŞTERİLER");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_ekle)
                        .addGap(18, 18, 18)
                        .addComponent(bt_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(bt_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_ad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_mail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ekle, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_guncelleActionPerformed
        // TODO add your handling code here:
         musteriduzenle yeni = new musteriduzenle();
      
       yeni.setVisible(true);
       this.setVisible(false);
       yeni.parent=this;
       
    }//GEN-LAST:event_bt_guncelleActionPerformed
    public static boolean harftestYap(String girilen){  
        int boyut=girilen.length();
        int deger[]=new int [boyut];
         for(int i=0;i<boyut;i++)
         {
                deger[i]=girilen.charAt(i);
                       
         }
         Boolean durum []=new Boolean[boyut];
           for(int i=0;i<boyut;i++)
           {
                 if(deger[i]>64 && deger[i]<91 || deger[i]>96 && deger[i]<123)
                    {
                         durum[i] = true;
                    }
                 else
                    {          
                         durum[i]=false;
                    }
          }
           int donus=0;
           for (int i = 0; i < boyut; i++)
           {
               if(durum[i]==true)
               {
                   donus+=1;
               }
            
            }
           if(donus==boyut)
           {       
                return true;
           } 
           else
               return false;
 }
       public static boolean sayitestYap(String girilen){  
        int boyut=girilen.length();
        int deger[]=new int [boyut];
         for(int i=0;i<boyut;i++)
         {
                deger[i]=girilen.charAt(i);
                       
         }
         Boolean durum []=new Boolean[boyut];
           for(int i=0;i<boyut;i++)
           {
                 if(deger[i]>47 && deger[i]<58)
                    {
                         durum[i] = true;
                    }
                 else
                    {          
                         durum[i]=false;
                    }
          }
           int donus=0;
           for (int i = 0; i < boyut; i++)
           {
               if(durum[i]==true)
               {
                   donus+=1;
               }
            
            }
           if(donus==boyut)
           {       
                return true;
           } 
           else
               return false;
 }
    private void bt_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ekleActionPerformed
        // TODO add your handling code here:
      
       if(!(harftestYap(txt_ad.getText())))
       {
           JOptionPane.showMessageDialog(null,"Lütfen isim  alanına sayı girmeyiniz!!!");
           
       }
       else  if(!(harftestYap(txt_soyad.getText())))
                {
                     JOptionPane.showMessageDialog(null,"Lütfen soyisim  alanına sayı girmeyiniz!!!");

                }
       else  if(!(sayitestYap(txt_tel.getText())))
                {
                     JOptionPane.showMessageDialog(null,"Telefon alanında harf olamaz!!!");

                }
       else
       { 
    if(txt_ad.getText().length()>0 && txt_tel.getText().length()>0 && txt_soyad.getText().length()>0)
    {
      
            String ad=txt_ad.getText();
            String soyad=txt_soyad.getText();
            String tel=txt_tel.getText();
            String mail=txt_mail.getText();
        
       
        try {
            vt.MusteriEkle(ad,soyad,tel,mail);
        } catch (SQLException ex) {
            Logger.getLogger(musteriler.class.getName()).log(Level.SEVERE, null, ex);
        }
       tb.MusteriTablosu(tb_musteriler);
        
       
        
    }//GEN-LAST:event_bt_ekleActionPerformed
    else
       {
              JOptionPane.showMessageDialog(null,"Zorunlu alanları doldurunuz!!!");
       }
    }
    }
    
    private void bt_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_silActionPerformed

    }//GEN-LAST:event_bt_silActionPerformed

    private void bt_silMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_silMouseClicked
        // TODO add your handling code here:
        
        int row=tb_musteriler.getSelectedRow();
        int col=0;
        int id=0; 
        if(row>=0)
        {   
        int dialogButton;
            dialogButton = JOptionPane.YES_NO_OPTION; 
        int dialogResult =JOptionPane.showConfirmDialog (null, "Müşteri bilğisi silinsin mi? ","Uyarı",dialogButton);
               if(dialogResult==0)
               {   id=(int) tb_musteriler.getValueAt(row, col);
        
                         vt.MusteriSil(id);
                          tb.MusteriTablosu(tb_musteriler);
               }
        }
        else
        {    
        JOptionPane.showMessageDialog(null,"Lütfen silmek istediniz müşteriyi seçiniz !!!");
        }
    }//GEN-LAST:event_bt_silMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriler().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ekle;
    private javax.swing.JButton bt_guncelle;
    private javax.swing.JButton bt_sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private javax.swing.JTable tb_musteriler;
    private javax.swing.JTextField txt_ad;
    private javax.swing.JTextField txt_mail;
    private javax.swing.JTextField txt_soyad;
    private javax.swing.JTextField txt_tel;
    // End of variables declaration//GEN-END:variables
}
