/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emlak_takip;


 
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ubeyd
 */
public class raporlar extends javax.swing.JFrame {

    /**
     * Creates new form raporlar
     */
    public Giris parent;
    public raporlar() {
        initComponents();       
        this.getContentPane().setBackground(Color.darkGray);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_kiralanan = new javax.swing.JButton();
        btn_satilan = new javax.swing.JButton();
        btn_emlaktip = new javax.swing.JButton();
        btn_isitmaturu = new javax.swing.JButton();
        btn_satilik = new javax.swing.JButton();
        btn_kiralik = new javax.swing.JButton();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMLAK TAKİP SİSTEMİ");

        btn_kiralanan.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_kiralanan.setText("Kiralanan Emlaklar");
        btn_kiralanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiralananActionPerformed(evt);
            }
        });

        btn_satilan.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_satilan.setText("Satilan Emlaklar");
        btn_satilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satilanActionPerformed(evt);
            }
        });

        btn_emlaktip.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_emlaktip.setText("Emlak Tipine Göre Satilan veya Kiralanan Emlaklar");
        btn_emlaktip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emlaktipActionPerformed(evt);
            }
        });

        btn_isitmaturu.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_isitmaturu.setText("İsitma Turune Göre Satilan veya Kiralanan Emlaklar");
        btn_isitmaturu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_isitmaturuActionPerformed(evt);
            }
        });

        btn_satilik.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_satilik.setText("Satilik Emlaklar");
        btn_satilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_satilikActionPerformed(evt);
            }
        });

        btn_kiralik.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        btn_kiralik.setText("Kiralik Emlaklar");
        btn_kiralik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_kiralikActionPerformed(evt);
            }
        });

        label1.setBackground(java.awt.Color.darkGray);
        label1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("RAPORLAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_isitmaturu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_emlaktip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_satilan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kiralanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_satilik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_kiralik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_kiralik, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_satilik, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_kiralanan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_satilan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_emlaktip, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_isitmaturu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_kiralikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiralikActionPerformed
        
            kiralik_emlak yeni = new kiralik_emlak();      
            yeni.setVisible(true);      
            
    }//GEN-LAST:event_btn_kiralikActionPerformed

    private void btn_satilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satilikActionPerformed
             satilik_emlak yeni = new satilik_emlak();      
            yeni.setVisible(true);      
            
    }//GEN-LAST:event_btn_satilikActionPerformed

    private void btn_kiralananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_kiralananActionPerformed
             kiralanan_emlak yeni = new kiralanan_emlak();      
            yeni.setVisible(true);      
            
    }//GEN-LAST:event_btn_kiralananActionPerformed

    private void btn_satilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_satilanActionPerformed
         satilan_emlak yeni = new satilan_emlak();      
            yeni.setVisible(true); 
    }//GEN-LAST:event_btn_satilanActionPerformed

    private void btn_emlaktipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emlaktipActionPerformed
        emlak_tipine_gore yeni = new emlak_tipine_gore();      
            yeni.setVisible(true); 
    }//GEN-LAST:event_btn_emlaktipActionPerformed

    private void btn_isitmaturuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_isitmaturuActionPerformed
        isitma_turune_gore yeni = new isitma_turune_gore();      
            yeni.setVisible(true); 
    }//GEN-LAST:event_btn_isitmaturuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(raporlar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new raporlar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_emlaktip;
    private javax.swing.JButton btn_isitmaturu;
    private javax.swing.JButton btn_kiralanan;
    private javax.swing.JButton btn_kiralik;
    private javax.swing.JButton btn_satilan;
    private javax.swing.JButton btn_satilik;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
