/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package emlak_takip;

import static emlak_takip.musteriler.sayitestYap;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.DropMode.INSERT;
import static javax.swing.GroupLayout.Alignment.values;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ubeyd
 */
public class satis_kira extends javax.swing.JFrame {

    /**
     * Creates new form satis_kira
     */
    VeriTabani vt = new VeriTabani();
    TabloBilgisi tb = new TabloBilgisi();
    public ilanlar parent;
    public satis_kira() 
    {
        initComponents();
        this.getContentPane().setBackground(Color.darkGray);
        tb.IlanTablosu(tb_ilanlar);
        tb.MusteriTablosu(tb_musteriler);
        tb.KayitlarTablosu(tb_kayitlar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_ilanlar = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_musteriler = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_fiyat = new javax.swing.JTextField();
        satis_kirala = new javax.swing.JButton();
        satistarihi = new com.toedter.calendar.JDateChooser();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_kayitlar = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EMLAK TAKİP SİSTEMİ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tb_ilanlar.setBackground(java.awt.Color.lightGray);
        tb_ilanlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_ilanlar);

        tb_musteriler.setBackground(java.awt.Color.lightGray);
        tb_musteriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_musteriler);

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Satış Fiyatı:");

        satis_kirala.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        satis_kirala.setText("Satış - Kiralama");
        satis_kirala.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                satis_kiralaMouseClicked(evt);
            }
        });
        satis_kirala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                satis_kiralaActionPerformed(evt);
            }
        });

        tb_kayitlar.setBackground(java.awt.Color.lightGray);
        tb_kayitlar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_kayitlar);

        jLabel4.setFont(new java.awt.Font("Bahnschrift", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tarih:");

        label1.setBackground(java.awt.Color.darkGray);
        label1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("SATILIK EMLAKLAR");

        label2.setBackground(java.awt.Color.darkGray);
        label2.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        label2.setForeground(new java.awt.Color(255, 255, 255));
        label2.setText("İLANLAR TABLOSU");

        label3.setBackground(java.awt.Color.darkGray);
        label3.setFont(new java.awt.Font("Bahnschrift", 1, 10)); // NOI18N
        label3.setForeground(new java.awt.Color(255, 255, 255));
        label3.setText("MÜŞTERİLER TABLOSU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addGap(37, 37, 37)
                        .addComponent(satistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(satis_kirala, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(satis_kirala, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addComponent(satistarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void satis_kiralaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_satis_kiralaActionPerformed
       
        
        
    }//GEN-LAST:event_satis_kiralaActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        ilanlar yeni = new ilanlar();
      
       yeni.setVisible(true);
    }//GEN-LAST:event_formWindowClosed
   
            
    private void satis_kiralaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_satis_kiralaMouseClicked
        // TODO add your handling code her
      
        String tarih = null;
        
            try
                  {
                     tarih = String.valueOf(satistarihi.getCalendar().getTime());
               
                  } 
                    catch(NullPointerException Tarihboş)
                    {
                          JOptionPane.showMessageDialog(null,"Tarih alanı boş olamaz!!!");

                    }

         
        if(txt_fiyat.getText().length()==0)
        {
            JOptionPane.showMessageDialog(null,"Fiyat bilgisini giriniz!!");
        }
       
       else if(!(sayitestYap(txt_fiyat.getText())))
        {
           JOptionPane.showMessageDialog(null,"Lütfen Fiyat alanına harf girmeyiniz!!!");
           
        }
       else if(tarih==null)
       {
         // try catch ile hata yakalanıyor bu if sadece eger hala  boş ise kayıt işlemi gerçekleşmesin diye

       }
       else
        {
                int row=tb_ilanlar.getSelectedRow();
                
                int row2=tb_musteriler.getSelectedRow();
                
              
          
              if(row==-1)
              {
                   JOptionPane.showMessageDialog(null,"Lütfen ilan seçiniz!!!");
              }   
              else if(row2==-1)
              {
                   JOptionPane.showMessageDialog(null,"Lütfen müşteri seçiniz");
              }
              else
              {
                  int col=0;
                  int id_ilan=(int)tb_ilanlar.getValueAt(row, col);
                  int id_musteri=(int)tb_musteriler.getValueAt(row, col);
                    try {                 
                            int fiyat=Integer.parseInt( txt_fiyat.getText());
                            
            
                            vt.satis_kirala(id_ilan,id_musteri, fiyat,tarih);
                            tb.KayitlarTablosu(tb_kayitlar);
                         }
                    catch (SQLException ex) 
                         {
                             Logger.getLogger(satis_kira.class.getName()).log(Level.SEVERE, null, ex);
                         }
                    tb.IlanTablosu(tb_ilanlar);
        }
        
        }
    }//GEN-LAST:event_satis_kiralaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(satis_kira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(satis_kira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(satis_kira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(satis_kira.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new satis_kira().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private javax.swing.JButton satis_kirala;
    private com.toedter.calendar.JDateChooser satistarihi;
    private javax.swing.JTable tb_ilanlar;
    private javax.swing.JTable tb_kayitlar;
    private javax.swing.JTable tb_musteriler;
    private javax.swing.JTextField txt_fiyat;
    // End of variables declaration//GEN-END:variables
}
